[package]
name = "aleph-alpha-client"
version = "0.4.1"
edition = "2021"
description = "Interact with large language models provided by the Aleph Alpha API in Rust code"
license = "MIT"
keywords = ["ai", "aleph-alpha"]
categories = ["api-bindings"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.9", features = ["json"] }
serde = { version = "1.0.134", features = ["derive"] }
serde_json = "1.0.79"
thiserror = "1.0.30"

[dev-dependencies]
dotenv = "0.15.0"
lazy_static = "1.4.0"
tokio = { version = "1.15.0", features = ["rt", "macros"] }
wiremock = "0.5.10"
