name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build
    - name: Run tests
      env:
        AA_API_TOKEN: ${{ secrets.AA_API_TOKEN }}
        AA_BASE_URL: ${{ secrets.AA_BASE_URL }}
      run: cargo test
